### ISSUE TITLE
License for utils.py

### ISSUE THREAD

**Issue by cameronneylon** [scholrly/orcid-python#4]
Hi, I've used your utils.py file as a library in another API wrapper (for the PLOS ALM API) and just wanted to check with you about the licensing. I'm planning to release my code under an Apache license if possible.

Cheers

Cameron

**Comment by mhluongo** [comment]
@cameronneylon, the library is MIT licensed. I'll add a copyright notice- if you could just include that downstream, that would be awesome.

**Comment by mhluongo** [comment]
I've posted a copy of the license to https://github.com/scholrly/orcid-python/blob/master/LICENSE-MIT.txt . Hope that helps!

**Comment by cameronneylon** [comment]
No problem. Thanks for that.

Cheers

Cameron
